// src/constants/exploreFilters.js
export const PROVINCES = [
  { id: 'tehran', label: 'تهران' },
  { id: 'alborz', label: 'البرز' },
  { id: 'isfahan', label: 'اصفهان' },
  { id: 'fars', label: 'فارس' },
  { id: 'khorasan', label: 'خراسان رضوی' },
];

export const CITIES = {
  tehran: [
    { id: 'tehran-city', label: 'تهران' },
    { id: 'shemiran', label: 'شمیرانات' },
    { id: 'rey', label: 'ری' },
  ],
  alborz: [
    { id: 'karaj', label: 'کرج' },
    { id: 'fardis', label: 'فردیس' },
  ],
  isfahan: [
    { id: 'isfahan-city', label: 'اصفهان' },
    { id: 'kashan', label: 'کاشان' },
  ],
  fars: [{ id: 'shiraz', label: 'شیراز' }],
  khorasan: [{ id: 'mashhad', label: 'مشهد' }],
};

export const BUSINESS_TYPES = [
  { id: 'salon', label: 'سالن زیبایی' },
  { id: 'clinic', label: 'کلینیک پوست و مو' },
  { id: 'nail', label: 'مرکز کاشت ناخن' },
  { id: 'laser', label: 'مرکز لیزر' },
  { id: 'keratin', label: 'مرکز کراتین و رنگ مو' },
  { id: 'makeup', label: 'میکاپ و گریم' },
];



// ✅ جدید: فیلتر تخفیف‌ها (جایگزین حداقل امتیاز)
export const DISCOUNT_FILTERS = [
  { id: '0', label: 'همه' },
  { id: '10', label: '۱۰٪ به بالا' },
  { id: '20', label: '۲۰٪ به بالا' },
  { id: '30', label: '۳۰٪ به بالا' },
  { id: '50', label: '۵۰٪ به بالا' },
];

export const MOCK_POSTS = [
  {
    id: 'p1',
    businessName: 'کلینیک زیبایی صدف',
    businessLogo: 'https://picsum.photos/100/100?random=1',
    businessId: 'b1',
    provinceId: 'tehran',
    cityId: 'tehran-city',
    businessTypeId: 'clinic',
    rating: 4.8,
    discount: 15, // ✅ جدید
    caption: 'فیشیال تخصصی VIP با استفاده از بهترین متریال روز دنیا ✨\nبرای رزرو نوبت به لینک بایو مراجعه کنید.',
    saved: false,
    source: 'business', // ✅ جدید: business یا magazine
    gallery: [
      'https://picsum.photos/800/800?random=1',
      'https://picsum.photos/800/800?random=2',
    ],
  },
  {
    id: 'p2',
    businessName: 'سالن زیبایی ماهرو',
    businessLogo: 'https://picsum.photos/100/100?random=2',
    businessId: 'b2',
    provinceId: 'tehran',
    cityId: 'shemiran',
    businessTypeId: 'makeup',
    rating: 4.6,
    discount: 0,
    caption: 'میکاپ و شینیون تخصصی عروس 👰‍♀',
    saved: true,
    source: 'business',
    gallery: ['https://picsum.photos/800/800?random=3'],
  },
  {
    id: 'p3',
    businessName: 'مرکز لیزر رویال',
    businessLogo: 'https://picsum.photos/100/100?random=3',
    businessId: 'b3',
    provinceId: 'isfahan',
    cityId: 'isfahan-city',
    businessTypeId: 'laser',
    rating: 4.9,
    discount: 25,
    caption: 'تخفیف ویژه جشنواره بهاره لیزر فول بادی 🌸',
    saved: false,
    source: 'business',
    gallery: [
      'https://picsum.photos/800/800?random=4',
      'https://picsum.photos/800/800?random=5',
      'https://picsum.photos/800/800?random=6',
    ],
  },
  {
    id: 'p4',
    businessName: 'کراتین سنتر النا',
    businessLogo: 'https://picsum.photos/100/100?random=4',
    businessId: 'b4',
    provinceId: 'alborz',
    cityId: 'karaj',
    businessTypeId: 'keratin',
    rating: 4.2,
    discount: 10,
    caption: 'احیای ۱۰۰٪ موهای آسیب‌دیده با مواد برزیلی تضمینی.',
    saved: false,
    source: 'business',
    gallery: ['https://picsum.photos/800/800?random=7'],
  },
  {
    id: 'p5',
    businessName: 'ناخن کار مریم',
    businessLogo: 'https://picsum.photos/100/100?random=5',
    businessId: 'b5',
    provinceId: 'fars',
    cityId: 'shiraz',
    businessTypeId: 'nail',
    rating: 4.5,
    discount: 0,
    caption: 'طراحی مینیمال و ژلیش ناخن طبیعی 💅',
    saved: false,
    source: 'business',
    gallery: ['https://picsum.photos/800/800?random=8'],
  },
  {
    id: 'p6',
    businessName: 'سالن زیبایی افرا',
    businessLogo: 'https://picsum.photos/100/100?random=6',
    businessId: 'b6',
    provinceId: 'tehran',
    cityId: 'tehran-city',
    businessTypeId: 'salon',
    rating: 3.8,
    discount: 35,
    caption: 'رنگ و لایت تخصصی با مواد اورجینال ایتالیایی 🎨',
    saved: false,
    source: 'business',
    gallery: [
      'https://picsum.photos/800/800?random=9',
      'https://picsum.photos/800/800?random=10',
    ],
  },
  // ✅ پست‌های مجله زیبانو (بدون قابلیت رزرو)
  {
    id: 'p10',
    businessName: 'مجله زیبانو',
    businessLogo: 'https://picsum.photos/100/100?random=90',
    businessId: 'magazine',
    provinceId: 'tehran',
    cityId: 'tehran-city',
    businessTypeId: 'salon',
    rating: 0,
    discount: 0,
    caption: '۱۰ ترند آرایشی پاییز ۱۴۰۳ که باید بشناسید! 🍂\n\nاز رنگ‌های گرم و خاکی تا تکنیک‌های جدید میکاپ، در این مقاله با جدیدترین ترندهای آرایشی فصل پاییز آشنا می‌شوید. این ترندها توسط متخصصان مجله زیبانو گردآوری شده و شامل نکات کاربردی برای اجرای آنها در خانه نیز می‌باشد.',
    saved: false,
    source: 'magazine', // ✅ مجله زیبانو
    gallery: [
      'https://picsum.photos/800/800?random=91',
      'https://picsum.photos/800/800?random=92',
      'https://picsum.photos/800/800?random=93',
    ],
  },
  {
    id: 'p11',
    businessName: 'مجله زیبانو',
    businessLogo: 'https://picsum.photos/100/100?random=90',
    businessId: 'magazine',
    provinceId: 'isfahan',
    cityId: 'isfahan-city',
    businessTypeId: 'clinic',
    rating: 0,
    discount: 0,
    caption: 'راهنمای کامل مراقبت از پوست در فصل سرما ❄️\n\nبا شروع فصل سرما، پوست ما بیشتر از هر زمان دیگری نیاز به مراقبت دارد. در این مقاله، متخصصان پوست زیبانو بهترین روش‌های مراقبت از پوست در زمستان را با شما به اشتراک می‌گذارند.',
    saved: false,
    source: 'magazine',
    gallery: [
      'https://picsum.photos/800/800?random=94',
      'https://picsum.photos/800/800?random=95',
    ],
  },
  {
    id: 'p12',
    businessName: 'مجله زیبانو',
    businessLogo: 'https://picsum.photos/100/100?random=90',
    businessId: 'magazine',
    provinceId: 'tehran',
    cityId: 'tehran-city',
    businessTypeId: 'salon',
    rating: 0,
    discount: 0,
    caption: 'تفاوت کراتین برزیلی و پروتئین تراپی چیست؟ 💇‍♀️\n\nبسیاری از افراد این دو روش را با هم اشتباه می‌گیرند. در این مقاله تخصصی، تفاوت‌های کلیدی، مزایا و معایب هر روش را بررسی می‌کنیم تا بتوانید بهترین انتخاب را برای موهای خود داشته باشید.',
    saved: false,
    source: 'magazine',
    gallery: ['https://picsum.photos/800/800?random=96'],
  },
  {
    id: 'p7',
    businessName: 'کلینیک ماه',
    businessLogo: 'https://picsum.photos/100/100?random=7',
    businessId: 'b7',
    provinceId: 'khorasan',
    cityId: 'mashhad',
    businessTypeId: 'clinic',
    rating: 4.7,
    discount: 20,
    caption: 'جوانسازی پوست با جدیدترین تکنولوژی روز دنیا 💫',
    saved: false,
    source: 'business',
    gallery: ['https://picsum.photos/800/800?random=11'],
  },
  {
    id: 'p8',
    businessName: 'آرایشگاه ستاره',
    businessLogo: 'https://picsum.photos/100/100?random=8',
    businessId: 'b8',
    provinceId: 'tehran',
    cityId: 'rey',
    businessTypeId: 'makeup',
    rating: 4.9,
    discount: 50,
    caption: 'گریم تخصصی عروس و نامزد با سبک اروپایی 💄',
    saved: false,
    source: 'business',
    gallery: [
      'https://picsum.photos/800/800?random=12',
      'https://picsum.photos/800/800?random=13',
      'https://picsum.photos/800/800?random=14',
    ],
  },
  {
    id: 'p9',
    businessName: 'ناخن گالری پریا',
    businessLogo: 'https://picsum.photos/100/100?random=9',
    businessId: 'b9',
    provinceId: 'alborz',
    cityId: 'fardis',
    businessTypeId: 'nail',
    rating: 4.4,
    discount: 0,
    caption: 'طراحی ناخن با سبک ژورنالی و مینیمال 💖',
    saved: false,
    source: 'business',
    gallery: ['https://picsum.photos/800/800?random=15'],
  },
];

// کمکی: تبدیل عدد به رقم فارسی
export const toPersianDigit = (str) =>
  String(str).replace(/[0-9]/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[d]);

// کمکی: یافتن label بر اساس id
export const findLabel = (arr, id) => arr.find((item) => item.id === id)?.label;