// src/screens/profile/paymentHistory/constants.js
export const MOCK_PAYMENTS = [
  {
    id: 'pay_1',
    type: 'deposit',
    title: 'بیعانه رزرو - فیشیال تخصصی پوست',
    businessName: 'سالن زیبایی نیلارام',
    businessLogo: 'https://picsum.photos/100/100?random=21',
    serviceName: 'فیشیال تخصصی پوست VIP',
    employeeName: 'سارا احمدی',
    date: '۱۴۰۳/۰۴/۱۰',
    dayName: 'شنبه',
    time: '۱۴:۳۲',
    month: 4,
    year: 1403,
    originalPrice: 750000,
    discountPercent: 10,
    discountAmount: 75000,
    totalPrice: 675000,
    depositAmount: 200000,
    paidAmount: 200000,
    remainingAmount: 475000,
    status: 'success',
    appointmentStatus: 'done',
    appointmentDate: '۱۴۰۳/۰۴/۱۵',
    appointmentTime: '۱۰:۳۰',
    paymentMethod: 'online',
    paymentGateway: 'درگاه بانک ملت',
    cardNumber: '6037 9918 **** 1234',
    cardBank: 'بانک ملی',
    trackingCode: 'TRK-1234567890',
    refNumber: 'REF-2024-001',
    verificationCode: '۵۸۹۲', // ✅ 4 رقم
  },
  {
    id: 'pay_2',
    type: 'deposit',
    title: 'بیعانه رزرو - لیزر فول بادی',
    businessName: 'مرکز لیزر رویال',
    businessLogo: 'https://picsum.photos/100/100?random=25',
    serviceName: 'لیزر فول بادی با دستگاه الکس',
    employeeName: 'دکتر رضایی',
    date: '۱۴۰۳/۰۴/۰۵',
    dayName: 'دوشنبه',
    time: '۱۱:۱۸',
    month: 4,
    year: 1403,
    originalPrice: 2500000,
    discountPercent: 15,
    discountAmount: 375000,
    totalPrice: 2125000,
    depositAmount: 500000,
    paidAmount: 500000,
    remainingAmount: 1625000,
    status: 'success',
    appointmentStatus: 'upcoming',
    appointmentDate: '۱۴۰۳/۰۴/۲۰',
    appointmentTime: '۱۶:۰۰',
    paymentMethod: 'online',
    paymentGateway: 'درگاه بانک پاسارگاد',
    cardNumber: '6219 8610 **** 5678',
    cardBank: 'بانک سامان',
    trackingCode: 'TRK-9876543210',
    refNumber: 'REF-2024-002',
    verificationCode: '۲۵۷۱', // ✅ 4 رقم
  },
  {
    id: 'pay_3',
    type: 'full_payment',
    title: 'پرداخت کامل - رنگ و لایت مو',
    businessName: 'سالن زیبایی افرا',
    businessLogo: 'https://picsum.photos/100/100?random=24',
    serviceName: 'رنگ و لایت مو با مواد ایتالیایی',
    employeeName: 'الناز کریمی',
    date: '۱۴۰۳/۰۳/۲۸',
    dayName: 'یکشنبه',
    time: '۱۸:۴۵',
    month: 3,
    year: 1403,
    originalPrice: 1800000,
    discountPercent: 20,
    discountAmount: 360000,
    totalPrice: 1440000,
    depositAmount: 0,
    paidAmount: 1440000,
    remainingAmount: 0,
    status: 'success',
    appointmentStatus: 'done',
    appointmentDate: '۱۴۰۳/۰۳/۲۸',
    appointmentTime: '۱۶:۰۰',
    paymentMethod: 'online',
    paymentGateway: 'درگاه بانک سامان',
    cardNumber: '6219 8610 **** 9012',
    cardBank: 'بانک سامان',
    trackingCode: 'TRK-5555555555',
    refNumber: 'REF-2024-003',
    verificationCode: '۷۴۵۶', // ✅ 4 رقم
  },
  {
    id: 'pay_4',
    type: 'deposit',
    title: 'بیعانه رزرو - کاشت ناخن ژلیش',
    businessName: 'ناخن گالری پریا',
    businessLogo: 'https://picsum.photos/100/100?random=26',
    serviceName: 'کاشت ناخن ژلیش طرح‌دار',
    employeeName: 'مریم',
    date: '۱۴۰۳/۰۳/۱۵',
    dayName: 'سه‌شنبه',
    time: '۰۹:۲۳',
    month: 3,
    year: 1403,
    originalPrice: 450000,
    discountPercent: 0,
    discountAmount: 0,
    totalPrice: 450000,
    depositAmount: 100000,
    paidAmount: 100000,
    remainingAmount: 350000,
    status: 'failed',
    failureReason: 'موجودی کارت کافی نبود',
    appointmentStatus: null,
    paymentMethod: 'online',
    paymentGateway: 'درگاه بانک ملت',
    cardNumber: '6037 9918 **** 3456',
    cardBank: 'بانک ملی',
    trackingCode: 'FAILED-0001',
    refNumber: 'REF-2024-004',
  },
  {
    id: 'pay_5',
    type: 'refund',
    title: 'استرداد بیعانه - لغو نوبت توسط سالن',
    businessName: 'سالن زیبایی افرا',
    businessLogo: 'https://picsum.photos/100/100?random=24',
    serviceName: 'رنگ و لایت مو',
    employeeName: 'الناز کریمی',
    date: '۱۴۰۳/۰۳/۰۶',
    dayName: 'دوشنبه',
    time: '۱۰:۱۵',
    month: 3,
    year: 1403,
    originalPrice: 1200000,
    discountPercent: 20,
    discountAmount: 240000,
    totalPrice: 960000,
    depositAmount: 300000,
    paidAmount: 300000,
    refundAmount: 225000,
    cancellationFee: 75000,
    status: 'refunded',
    appointmentStatus: 'cancelled',
    appointmentDate: '۱۴۰۳/۰۳/۰۵',
    appointmentTime: '۱۱:۰۰',
    paymentMethod: 'refund',
    cardNumber: '6037 9918 **** 1234',
    cardBank: 'بانک ملی',
    trackingCode: 'TRK-7777777777',
    refNumber: 'REF-2024-005',
  },
];

export const STATUS_META = {
  success:  { label: 'موفق',       color: '#43A047', icon: 'check-circle', bg: '#43A04715' },
  failed:   { label: 'ناموفق',     color: '#E53935', icon: 'cancel',       bg: '#E5393515' },
  pending:  { label: 'در انتظار',   color: '#FFA000', icon: 'schedule',     bg: '#FFA00015' },
  refunded: { label: 'مسترد شده',   color: '#1E88E5', icon: 'undo',         bg: '#1E88E515' },
};

export const APPOINTMENT_STATUS_META = {
  upcoming:  { label: 'نوبت آینده',  color: '#2196F3', icon: 'event-available' },
  done:      { label: 'انجام شده',    color: '#43A047', icon: 'task-alt' },
  cancelled: { label: 'لغو شده',      color: '#E53935', icon: 'cancel' },
};

export const PAYMENT_METHOD_META = {
  online: { label: 'درگاه بانکی',     icon: 'credit-card',            color: '#2196F3' },
  wallet: { label: 'کیف پول',         icon: 'account-balance-wallet', color: '#9C27B0' },
  refund: { label: 'استرداد به کارت', icon: 'undo',                   color: '#1E88E5' },
};

export const PAYMENT_TYPE_META = {
  deposit:          { label: 'بیعانه',        color: '#FF9800', icon: 'account-balance-wallet' },
  full_payment:     { label: 'پرداخت کامل',    color: '#2196F3', icon: 'payments' },
  service_purchase: { label: 'خرید سرویس',    color: '#9C27B0', icon: 'workspace-premium' },
  refund:           { label: 'استرداد',        color: '#1E88E5', icon: 'undo' },
};

export const MONTHS = [
  { id: 0,  label: 'همه ماه‌ها' },
  { id: 1,  label: 'فروردین' },
  { id: 2,  label: 'اردیبهشت' },
  { id: 3,  label: 'خرداد' },
  { id: 4,  label: 'تیر' },
  { id: 5,  label: 'مرداد' },
  { id: 6,  label: 'شهریور' },
  { id: 7,  label: 'مهر' },
  { id: 8,  label: 'آبان' },
  { id: 9,  label: 'آذر' },
  { id: 10, label: 'دی' },
  { id: 11, label: 'بهمن' },
  { id: 12, label: 'اسفند' },
];

export const YEARS = [
  { id: 0,    label: 'همه سال‌ها' },
  { id: 1403, label: '۱۴۰۳' },
  { id: 1402, label: '۱۴۰۲' },
  { id: 1401, label: '۱۴۰۱' },
];